project:
  type: website
  output-dir: docs
  resources: 
    - CNAME

website:
  title: "Anant's Blog" 
  description: "A blog about Mathematics, Physics, Machine Learning, and EdTech."
  page-navigation: true
  
  site-url: https://anantkumar.online
  favicon: favicon/favicon.ico
  
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/kaymant
      - icon: linkedin
        href: https://www.linkedin.com/in/an-ant/
      - icon: youtube
        href: https://www.youtube.com/@AnantKumarPlus
 
  sidebar:
    contents:
      - section: "Recent Posts"
        contents: posts/
        sort: "date desc"
       
  page-footer:
    left: "Copyright 2026, Anant"
    right:
      - text: "All posts"
        href: index.qmd
 
  comments:
    giscus:
      repo: kaymant/blogs
      repo-id: R_kgDORBjjTg # Provided by giscus.app
      category: General
      category-id: DIC_kwDORBjjTs4C2ifr # Provided by giscus.app
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      theme: light # or dark

# OPTIMIZATION FOR ML/MATH
# This saves the results of your code. Quarto won't re-run your 
# ML training cells unless you modify that specific file.
execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    bibliography: references.bib
